name: lasvegaslifecoach
favicon: null
layout_spectrum: 0.7432
typography_spectrum: 0.75292
title: 'Offering the best in life coaching, therapy and psychology '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6da2d6'
    - '#005da3'
    - '#fecd91'
    - '#010000'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
